services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src